---
language: go

matrix:
  include:
    - go: 1.10.x
      script: go test -v ./...
    - go: 1.11.x
      env: GO111MODULE=on
      script: go test -v -mod=vendor ./...
    - go: 1.12.x
      env: GO111MODULE=on
      script: go test -v -mod=vendor ./...
    - go: tip
      env: GO111MODULE=on
      script: go test -v -mod=vendor ./...
